backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    files:
      - label: "Services Data"
        name: "services"
        file: "src/data/services.json"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Hero Image", name: "heroImage", widget: "image" }
              - { label: "Overview", name: "overview", widget: "text" }
              - { label: "Features", name: "features", widget: "list", field: { label: "Feature", name: "feature", widget: "string" } }
              - { label: "Benefits", name: "benefits", widget: "list", field: { label: "Benefit", name: "benefit", widget: "string" } }
              - label: "Process Steps"
                name: "process"
                widget: "list"
                fields:
                  - { label: "Step", name: "step", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
              - label: "Pricing Plans"
                name: "pricing"
                widget: "list"
                fields:
                  - { label: "Tier", name: "tier", widget: "string" }
                  - { label: "Price", name: "price", widget: "string" }
                  - { label: "Popular", name: "popular", widget: "boolean", default: false }
                  - { label: "Features", name: "features", widget: "list", field: { label: "Feature", name: "feature", widget: "string" } }
              - label: "Statistics"
                name: "stats"
                widget: "list"
                fields:
                  - { label: "Number", name: "number", widget: "string" }
                  - { label: "Label", name: "label", widget: "string" }

  - name: "testimonials"
    label: "Testimonials"
    files:
      - label: "Testimonials Data"
        name: "testimonials"
        file: "src/data/testimonials.json"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Company", name: "company", widget: "string" }
              - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5 }
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Full Testimonial", name: "fullTestimonial", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Service", name: "service", widget: "string" }
              - { label: "Results", name: "results", widget: "list", field: { label: "Result", name: "result", widget: "string" } }

  - name: "team"
    label: "Team"
    files:
      - label: "Team Data"
        name: "team"
        file: "src/data/team.json"
        fields:
          - label: "Team Members"
            name: "team"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Bio", name: "bio", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "faqs"
    label: "FAQs"
    files:
      - label: "FAQs Data"
        name: "faqs"
        file: "src/data/faqs.json"
        fields:
          - label: "FAQs"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }

  - name: "blog"
    label: "Blog Posts"
    files:
      - label: "Blog Data"
        name: "blog"
        file: "src/data/blog.json"
        fields:
          - label: "Blog Posts"
            name: "posts"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Excerpt", name: "excerpt", widget: "text" }
              - { label: "Content", name: "content", widget: "text" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Read Time", name: "readTime", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Slug", name: "slug", widget: "string" }
              - label: "Author"
                name: "author"
                widget: "object"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Image", name: "image", widget: "image" }

  - name: "jobs"
    label: "Job Listings"
    files:
      - label: "Jobs Data"
        name: "jobs"
        file: "src/data/jobs.json"
        fields:
          - label: "Job Listings"
            name: "jobs"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Department", name: "department", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Experience", name: "experience", widget: "string" }
              - { label: "Salary", name: "salary", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Requirements", name: "requirements", widget: "list", field: { label: "Requirement", name: "requirement", widget: "string" } }
              - { label: "Benefits", name: "benefits", widget: "list", field: { label: "Benefit", name: "benefit", widget: "string" } }
              - { label: "Posted Date", name: "posted", widget: "datetime" }

  - name: "site_settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "src/data/settings.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - label: "Contact Info"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Address", name: "address", widget: "text" }
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string" }
              - { label: "Twitter", name: "twitter", widget: "string" }
              - { label: "LinkedIn", name: "linkedin", widget: "string" }
              - { label: "Instagram", name: "instagram", widget: "string" }
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
              - { label: "CTA Text", name: "ctaText", widget: "string" }